#!/usr/bin/env python3

import os, shutil

print("\nCompiling LaTeX...")
cmd = "cd ./latex && latexmk -pdf -outdir=../.cache/latexmk ./opal"
print(f"$ {cmd}")
os.system(cmd)

print(f"\nPackaging LaTeX PDF...")
if os.path.exists("./build/opal.pdf"):
    os.remove("./build/opal.pdf")
os.makedirs("./build", exist_ok=True)
shutil.copy("./.cache/latexmk/opal.pdf", "./build/opal.pdf")
